IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-08:00) Pacific Time (US & Canada)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-08:00) Pacific Time (US & Canada)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-07:00) Arizona')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-07:00) Arizona') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-07:00) Chihuahua, La Paz, Mazatlan')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-07:00) Chihuahua, La Paz, Mazatlan') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-07:00) Mountain Time (US & Canada)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-07:00) Mountain Time (US & Canada)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-06:00) Central America')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-06:00) Central America') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-06:00) Central Time (US & Canada)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-06:00) Central Time (US & Canada)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-06:00) Guadalajara, Mexico City, Monterrey')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-06:00) Guadalajara, Mexico City, Monterrey') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-06:00) Saskatchewan')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-06:00) Saskatchewan') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-05:00) Bogota, Lima, Quito, Rio Branco')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-05:00) Bogota, Lima, Quito, Rio Branco') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-05:00) Eastern Time (US & Canada)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-05:00) Eastern Time (US & Canada)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-05:00) Indiana (East)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-05:00) Indiana (East)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-04:30) Caracas')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-04:30) Caracas') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-04:00) Asuncion')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-04:00) Asuncion') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-04:00) Atlantic Time (Canada)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-04:00) Atlantic Time (Canada)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-04:00) Cuiaba')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-04:00) Cuiaba') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-04:00) Georgetown, La Paz, Manaus, San Juan')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-04:00) Georgetown, La Paz, Manaus, San Juan') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-04:00) Santiago')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-04:00) Santiago') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:30) Newfoundland')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:30) Newfoundland') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:00) Brasilia')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:00) Brasilia') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:00) Buenos Aires')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:00) Buenos Aires') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:00) Cayenne, Fortaleza')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:00) Cayenne, Fortaleza') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:00) Greenland')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:00) Greenland') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:00) Montevideo')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:00) Montevideo') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-03:00) Salvador')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-03:00) Salvador') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-02:00) Coordinated Universal Time-02')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-02:00) Coordinated Universal Time-02') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-02:00) Mid-Atlantic - Old')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-02:00) Mid-Atlantic - Old') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-01:00) Azores')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-01:00) Azores') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC-01:00) Cape Verde Is.')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC-01:00) Cape Verde Is.') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC) Casablanca')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC) Casablanca') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC) Coordinated Universal Time')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC) Coordinated Universal Time') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC) Dublin, Edinburgh, Lisbon, London')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC) Dublin, Edinburgh, Lisbon, London') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC) Monrovia, Reykjavik')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC) Monrovia, Reykjavik') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+01:00) Brussels, Copenhagen, Madrid, Paris')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+01:00) Brussels, Copenhagen, Madrid, Paris') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+01:00) West Central Africa')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+01:00) West Central Africa') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+01:00) Windhoek')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+01:00) Windhoek') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Amman')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Amman') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Athens, Bucharest')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Athens, Bucharest') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Beirut')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Beirut') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Cairo')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Cairo') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Damascus')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Damascus') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) E. Europe')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) E. Europe') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Harare, Pretoria')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Harare, Pretoria') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Istanbul')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Istanbul') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Jerusalem')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Jerusalem') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+02:00) Tripoli')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+02:00) Tripoli') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+03:00) Baghdad')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+03:00) Baghdad') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+03:00) Kaliningrad, Minsk')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+03:00) Kaliningrad, Minsk') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+03:00) Kuwait, Riyadh')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+03:00) Kuwait, Riyadh') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+03:00) Nairobi')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+03:00) Nairobi') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+03:30) Tehran')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+03:30) Tehran') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:00) Abu Dhabi, Muscat')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:00) Abu Dhabi, Muscat') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:00) Baku')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:00) Baku') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:00) Moscow, St. Petersburg, Volgograd')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:00) Moscow, St. Petersburg, Volgograd') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:00) Port Louis')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:00) Port Louis') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:00) Tbilisi')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:00) Tbilisi') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:00) Yerevan')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:00) Yerevan') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+04:30) Kabul')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+04:30) Kabul') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+05:00) Ashgabat, Tashkent')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+05:00) Ashgabat, Tashkent') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+05:00) Islamabad, Karachi')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+05:00) Islamabad, Karachi') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+05:30) Sri Jayawardenepura')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+05:30) Sri Jayawardenepura') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+05:45) Kathmandu')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+05:45) Kathmandu') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+06:00) Astana')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+06:00) Astana') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+06:00) Dhaka')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+06:00) Dhaka') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+06:00) Ekaterinburg')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+06:00) Ekaterinburg') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+06:30) Yangon (Rangoon)')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+06:30) Yangon (Rangoon)') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+07:00) Bangkok, Hanoi, Jakarta')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+07:00) Bangkok, Hanoi, Jakarta') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+07:00) Novosibirsk')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+07:00) Novosibirsk') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+08:00) Krasnoyarsk')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+08:00) Krasnoyarsk') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+08:00) Kuala Lumpur, Singapore')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+08:00) Kuala Lumpur, Singapore') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+08:00) Perth')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+08:00) Perth') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+08:00) Taipei')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+08:00) Taipei') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+08:00) Ulaanbaatar')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+08:00) Ulaanbaatar') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+09:00) Irkutsk')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+09:00) Irkutsk') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+09:00) Osaka, Sapporo, Tokyo')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+09:00) Osaka, Sapporo, Tokyo') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+09:00) Seoul')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+09:00) Seoul') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+09:30) Adelaide')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+09:30) Adelaide') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+09:30) Darwin')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+09:30) Darwin') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+10:00) Brisbane')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+10:00) Brisbane') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+10:00) Canberra, Melbourne, Sydney')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+10:00) Canberra, Melbourne, Sydney') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+10:00) Guam, Port Moresby')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+10:00) Guam, Port Moresby') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+10:00) Hobart')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+10:00) Hobart') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+10:00) Yakutsk')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+10:00) Yakutsk') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+11:00) Solomon Is., New Caledonia')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+11:00) Solomon Is., New Caledonia') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+11:00) Vladivostok')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+11:00) Vladivostok') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+12:00) Auckland, Wellington')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+12:00) Auckland, Wellington') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+12:00) Coordinated Universal Time+12')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+12:00) Coordinated Universal Time+12') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+12:00) Fiji')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+12:00) Fiji') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+12:00) Magadan')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+12:00) Magadan') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+12:00) Petropavlovsk-Kamchatsky - Old')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+12:00) Petropavlovsk-Kamchatsky - Old') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+13:00) Nuku''alofa')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+13:00) Nuku''alofa') END
IF NOT EXISTS (SELECT 1 FROM [Core].TimeZone WHERE Name='(UTC+13:00) Samoa')BEGIN INSERT INTO [Core].TimeZone(Name) VALUES('(UTC+13:00) Samoa') END
